### PR TITLE
Link external documentation and render description as markdown

### PR DESCRIPTION
**Pull request by jeffersongirao**
Hey there @dweber019!

Thanks a lot for your work on the Spectral Lint Plugin for Backstage! 🙌 

In this PR I'm proposing to render a documentation URL link when that is available. Also to render the description as markdown (I think that is how some rules are documented out there, the spotlight one was added as an example). 

Please let me know your thoughts on that! 🙂

### CODE REVIEW

**Comment by dweber019** [comment]
@jeffersongirao Thanks 🙏 will have a look at this over the weekend. Cheers

**Review by dweber019 — APPROVED** [review]
Expect from linting and a changeset every looks good.
https://github.com/dweber019/backstage-plugins/blob/main/CONTRIBUTING.md#creating-changesets

**Comment by jeffersongirao** [comment]
@dweber019 thanks for the quick reply! I've just added the changeset 👍.

**Comment by dweber019** [comment]
@jeffersongirao Should be available in a few minutes.

**Pull request merged**
